webtalk_init -webtalk_dir E:/University/gp/GITverilog/Hardware-CNN-Acceleration-/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/TestPer_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat May  7 18:14:11 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "dbc8a6bb-d477-47da-9df3-6d1961591c8c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9c695bf64364463da57055b55c983732" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "19" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 3 1300X Quad-Core Processor          " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10100 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "122.30_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "185748_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1976712926 -regid "" -xml E:/University/gp/GITverilog/Hardware-CNN-Acceleration-/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/TestPer_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/University/gp/GITverilog/Hardware-CNN-Acceleration-/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/TestPer_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/University/gp/GITverilog/Hardware-CNN-Acceleration-/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/TestPer_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
