webtalk_init -webtalk_dir E:/University/gp/GITverilog/Hardware-CNN-Acceleration-/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/TestPer_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri May  6 18:28:01 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "dbc8a6bb-d477-47da-9df3-6d1961591c8c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9c695bf64364463da57055b55c983732" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "121" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 3 1300X Quad-Core Processor          " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "16" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "1454 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "1950 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "14857" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "7350" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "15.83_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "331412_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2696356774 -regid "" -xml E:/University/gp/GITverilog/Hardware-CNN-Acceleration-/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/TestPer_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/University/gp/GITverilog/Hardware-CNN-Acceleration-/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/TestPer_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/University/gp/GITverilog/Hardware-CNN-Acceleration-/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/TestPer_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
