# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/MemBlk_3/MemBlk_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MemBlk_3 || ORIG_REF_NAME==MemBlk_3} -quiet] -quiet

# IP: ip/MemBlk_2/MemBlk_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MemBlk_2 || ORIG_REF_NAME==MemBlk_2} -quiet] -quiet

# IP: ip/MemBlk_1/MemBlk_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MemBlk_1 || ORIG_REF_NAME==MemBlk_1} -quiet] -quiet
