# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/University/Graduation_Project/Hardware-CNN-Acceleration-/project_1/project_1.srcs/sources_1/ip/MemBlk_1/MemBlk_1.xci
# IP: The module: 'MemBlk_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/University/Graduation_Project/Hardware-CNN-Acceleration-/project_1/project_1.srcs/sources_1/ip/MemBlk_1/MemBlk_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MemBlk_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/University/Graduation_Project/Hardware-CNN-Acceleration-/project_1/project_1.srcs/sources_1/ip/MemBlk_1/MemBlk_1.xci
# IP: The module: 'MemBlk_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/University/Graduation_Project/Hardware-CNN-Acceleration-/project_1/project_1.srcs/sources_1/ip/MemBlk_1/MemBlk_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MemBlk_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
