# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Youssef/GraduationProject/Github/Hardware-CNN-Acceleration-/project_1/project_1.srcs/sources_1/ip/DenseW2/DenseW2.xci
# IP: The module: 'DenseW2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Youssef/GraduationProject/Github/Hardware-CNN-Acceleration-/project_1/project_1.srcs/sources_1/ip/DenseW2/DenseW2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DenseW2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/Youssef/GraduationProject/Github/Hardware-CNN-Acceleration-/project_1/project_1.srcs/sources_1/ip/DenseW2/DenseW2.xci
# IP: The module: 'DenseW2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Youssef/GraduationProject/Github/Hardware-CNN-Acceleration-/project_1/project_1.srcs/sources_1/ip/DenseW2/DenseW2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DenseW2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
