# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/University/gp/GITverilog/Hardware-CNN-Acceleration-/project_1/project_1.srcs/sources_1/ip/DenseW0/DenseW0.xci
# IP: The module: 'DenseW0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/University/gp/GITverilog/Hardware-CNN-Acceleration-/project_1/project_1.srcs/sources_1/ip/DenseW0/DenseW0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DenseW0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/University/gp/GITverilog/Hardware-CNN-Acceleration-/project_1/project_1.srcs/sources_1/ip/DenseW0/DenseW0.xci
# IP: The module: 'DenseW0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/University/gp/GITverilog/Hardware-CNN-Acceleration-/project_1/project_1.srcs/sources_1/ip/DenseW0/DenseW0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DenseW0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
