# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/work/college/5-Senior 2/Semester 2/Graduation Project 2/GP Codes/Hardware-CNN-Acceleration-/project_1/project_1.srcs/sources_1/ip/DenseW3/DenseW3.xci
# IP: The module: 'DenseW3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/work/college/5-Senior 2/Semester 2/Graduation Project 2/GP Codes/Hardware-CNN-Acceleration-/project_1/project_1.srcs/sources_1/ip/DenseW3/DenseW3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DenseW3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/work/college/5-Senior 2/Semester 2/Graduation Project 2/GP Codes/Hardware-CNN-Acceleration-/project_1/project_1.srcs/sources_1/ip/DenseW3/DenseW3.xci
# IP: The module: 'DenseW3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/work/college/5-Senior 2/Semester 2/Graduation Project 2/GP Codes/Hardware-CNN-Acceleration-/project_1/project_1.srcs/sources_1/ip/DenseW3/DenseW3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DenseW3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
