# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/University/gp/GITverilog/Hardware-CNN-Acceleration-/project_1/project_1.srcs/sources_1/ip/C1W/C1W.xci
# IP: The module: 'C1W' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/University/gp/GITverilog/Hardware-CNN-Acceleration-/project_1/project_1.srcs/sources_1/ip/C1W/C1W_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'C1W'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/University/gp/GITverilog/Hardware-CNN-Acceleration-/project_1/project_1.srcs/sources_1/ip/C1W/C1W.xci
# IP: The module: 'C1W' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/University/gp/GITverilog/Hardware-CNN-Acceleration-/project_1/project_1.srcs/sources_1/ip/C1W/C1W_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'C1W'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
